server:
  port: 8080
  address: 0.0.0.0

spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  application:
    name: qrcode-login-service

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

qrcode:
  expire-minutes: 5
  polling-seconds: 2

jwt:
  secret: HoFUHAJ1yxGnHDx8zL0Zp4RhpmGBk1m5XyCbN9qW3eM=
  expiration: 86400

logging:
  level:
    root: INFO
    com.example.qrcodelogin: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/qrcode-login.log
    max-size: 10MB
    max-history: 7 